import { SuggestionData } from "../../types/menu";
import { Kitchen, Organisation, User } from "../../types/profile";

export const mockSuggestions: SuggestionData = {
  categories: [
    "Appetizers",
    "Main Course",
    "Desserts",
    "Beverages",
    "Salads",
    "Soups",
    "Pasta",
    "Pizza",
    "Sandwiches",
    "Burgers",
  ],
  items: [
    "Margherita Pizza",
    "Chicken Caesar Salad",
    "Beef Burger",
    "Pasta Carbonara",
    "Tomato Soup",
    "Grilled Chicken",
    "Fish Tacos",
    "Vegetable Stir Fry",
    "Chocolate Cake",
    "Fresh Juice",
  ],
  ingredients: [
    "Tomatoes",
    "Onions",
    "Garlic",
    "Olive Oil",
    "Basil",
    "Oregano",
    "Mozzarella",
    "Chicken",
    "Beef",
    "Fish",
    "Lettuce",
    "Spinach",
    "Bell Peppers",
    "Mushrooms",
    "Cheese",
    "Cream",
    "Butter",
    "Salt",
    "Pepper",
    "Lemon",
  ],
  tags: [
    "Spicy",
    "Mild",
    "Popular",
    "Chef Special",
    "Healthy",
    "Low Calorie",
    "Gluten Free",
    "Dairy Free",
    "Organic",
    "Seasonal",
    "Quick Serve",
    "Premium",
  ],
  addOnItems: [
    "Extra Cheese",
    "Extra Sauce",
    "Garlic Bread",
    "French Fries",
    "Onion Rings",
    "Coleslaw",
    "Pickles",
    "Bacon",
    "Avocado",
    "Mushrooms",
    "Large Size",
    "Extra Large",
    "Double Portion",
    "10% Off",
    "20% Off",
    "Buy 1 Get 1",
    "Happy Hour",
  ],
  quantityTypes: [
    "Full",
    "Half",
    "Quarter",
    "Large",
    "Medium",
    "Small",
    "Regular",
    "Jumbo",
    "Family Size",
    "Single Serve",
    "Double",
    "Triple",
  ],
};

export const addOnCategories = [
  { id: "quantity", title: "Quantity" },
  { id: "offers", title: "Offers" },
  { id: "extras", title: "Extras" },
  { id: "addons", title: "Add-ons" },
];

export const mockUser: User = {
  id: "1",
  email: "john.doe@example.com",
  firstName: "John",
  lastName: "Doe",
  website: "https://johndoe.com",
  facebook: "https://facebook.com/johndoe",
  avatar:
    "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=1",
  fullName: "John Doe",
};


